<a href="https://colab.research.google.com/github/leehg9805/S-W-/blob/main/%EB%A1%9C%EC%A7%80%EC%8A%A4%ED%8B%B1_%ED%9A%8C%EA%B7%80%EC%9D%98_%EA%B8%B0%EC%B4%88%2C_iris_%ED%8F%89%EA%B0%80%EB%B0%A9%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 로지스틱 회귀란?

In [ ]:
from sklearn.metrics import confusion_matrix
y_true = [1,0,1,1,0,1]
y_pred = [0,0,1,1,0,1]
confusion_matrix(y_true, y_pred)

array([[2, 0],
       [1, 3]])

In [ ]:
tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
(tn,fp,fn,tp)

(2, 0, 1, 3)

In [ ]:
 import numpy as np
 from sklearn.metrics import accuracy_score
 y_pred = np.array([0,1,1,0])
 y_true = np.array([0,1,0,0])
 accuracy_score(y_true, y_pred)

0.75

In [ ]:
sum(y_true==y_pred)/len(y_pred)

0.75

In [ ]:
import numpy as np
import sklearn
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

y_pred =np.array([0,1,1,0,1,1,1,0])
y_true =np.array([0,1,0,0,0,0,1,0])

In [ ]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
data_url = 'http://www-stat.wharton.upenn.edu/~waterman/DataSets/uva.txt'

df = pd.read_table(data_url)
df[:5]

who  Newbie   Age  Gender Household Income Sexual Preference  \
0  id74364       0  54.0    Male           $50-74          Gay male   
1  id84505       0  39.0  Female        Over $100      Heterosexual   
2  id84509       1  49.0  Female           $40-49      Heterosexual   
3  id87028       1  22.0  Female           $40-49      Heterosexual   
4  id76087       0  20.0    Male           $30-39          Bisexual   

      Country Education Attainment Major Occupation Marital Status  \
0     Ontario         Some College         Computer          Other   
1      Sweden         Professional            Other          Other   
2  Washington         Some College       Management          Other   
3     Florida         Some College         Computer        Married   
4  New Jersey         Some College        Education         Single   

  Years on Internet  
0            4-6 yr  
1            1-3 yr  
2        Under 6 mo  
3           6-12 mo  
4            1-3 yr

In [ ]:
df.pop('who')
df.pop('Country')
df.pop('Years on Internet')

df.dtypes

Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Education Attainment     object
Major Occupation         object
Marital Status           object
dtype: object

In [ ]:
category_cols = ['Gender', 'Household Income', 'Sexual Preference', 'Education Attainment',
                 'Major Occupation', 'Marital Status']

for col in category_cols:
  df[col] = df[col].astype('category')

df.dtypes

Newbie                     int64
Age                      float64
Gender                  category
Household Income        category
Sexual Preference       category
Education Attainment    category
Major Occupation        category
Marital Status          category
dtype: object

In [ ]:
df_onehot = pd.get_dummies(df)
df_onehot.shape

(19583, 38)

In [ ]:
df_onehot.isnull().sum()

Newbie                                 0
Age                                  561
Gender_Female                          0
Gender_Male                            0
Household Income_$10-19                0
Household Income_$20-29                0
Household Income_$30-39                0
Household Income_$40-49                0
Household Income_$50-74                0
Household Income_$75-99                0
Household Income_Over $100             0
Household Income_Under $10             0
Sexual Preference_Bisexual             0
Sexual Preference_Gay male             0
Sexual Preference_Heterosexual         0
Sexual Preference_Lesbian              0
Sexual Preference_Transgender          0
Sexual Preference_na                   0
Education Attainment_College           0
Education Attainment_Doctoral          0
Education Attainment_Grammar           0
Education Attainment_High School       0
Education Attainment_Masters           0
Education Attainment_Other             0
Education Attain

In [ ]:
df_onehot.loc[pd.isnull(df_onehot['Age']),'Age']=df_onehot['Age'].mean()

In [ ]:
x_data = df_onehot.iloc[:,1:].values
y_data = df_onehot.iloc[:,0].values.reshape(-1,1)
y_data.shape, x_data.shape

((19583, 1), (19583, 37))

In [ ]:
from sklearn import preprocessing

min_max_scaler =preprocessing.MinMaxScaler()
x_data = min_max_scaler.fit_transform(x_data)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x_data, y_data, test_size=0.33, random_state=42
)

In [ ]:
X_train.shape, X_test.shape

((13120, 37), (6463, 37))

penalty : 규제에 사용 된 기준을 지정 (l1, l2, elasticnet, none) 
default : l2
dual : 이중 또는 초기 공식
tol : 정밀도
C : 규제 강도
fit_intercept : 모형에 상수항 (절편)이 있는가 없는가를 결정하는 인수 (default : True)
intercept_scaling : 정규화 효과 정도
class_weight : 클래스의 가중치
random_state : 난수 seed 설정
solver : 최적화 문제에 사용하는 알고리즘
max_iter : 계산에 사용할 작업 수
multi_class : 다중 분류 시에 (ovr, multinomial, auto)로 설정
verbose : 동작 과정에 대한 출력 메시지
warm_start : 이전 모델을 초기화로 적합하게 사용할 것인지 여부
n_jobs : 병렬 처리 할 때 사용되는 CPU 코어 수
l1_ratio : L1 규제의 비율(Elastic-Net 믹싱 파라미터 경우에만 사용)







In [ ]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(fit_intercept=True)
logreg.fit(X_train, y_train.flatten())

LogisticRegression()

In [ ]:
logreg.predict(X_test[:5])

array([0, 0, 0, 0, 0])

In [ ]:
logreg.predict_proba(X_test[:5])

array([[0.56843257, 0.43156743],
       [0.91112573, 0.08887427],
       [0.79481084, 0.20518916],
       [0.85841562, 0.14158438],
       [0.62764602, 0.37235398]])

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

y_true = y_test.copy()
y_pred = logreg.predict(X_test)
confusion_matrix(y_true, y_pred)

array([[4487,  275],
       [1350,  351]])

In [ ]:
accuracy_score(y_true, y_pred)

0.7485687761101656

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

kfold = KFold(n_splits=5)
cv_accuracy = []
print(features.shape)

(150, 4)


In [ ]:
n_iter = 0

for train_index, test_index in kfold.split(features):
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter +=1

  accuracy = np.round(accuracy_score(y_test,pred),4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, \검증 데이터 크기:{3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)


print('\n## 평균 검증 정확도:',np.mean(cv_accuracy))



#1 교차 검증 정확도 :1.0, 학습 데이터 크기: 120, \검증 데이터 크기:30
#1 검증 세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :0.9667, 학습 데이터 크기: 120, \검증 데이터 크기:30
#2 검증 세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 :0.8667, 학습 데이터 크기: 120, \검증 데이터 크기:30
#3 검증 세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기: 120, \검증 데이터 크기:30
#4 검증 세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 :0.7333, 학습 데이터 크기: 120, \검증 데이터 크기:30
#5 검증 세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


In [ ]:
from sklearn.model_selection import StratifiedKFold

dt_clf = DecisionTreeClassifier(random_state=156)
skfold = StratifiedKFold(n_splits= 3)
n_iter = 0
cv_accuracy=[]

for train_index, test_index in skfold.split(features,label):
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter +=1

  accuracy = np.round(accuracy_score(y_test,pred),4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, \검증 데이터 크기:{3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)


print('\n## 평균 검증 정확도:',np.mean(cv_accuracy))



#1 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, \검증 데이터 크기:50
#1 검증 세트 인덱스: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 :0.94, 학습 데이터 크기: 100, \검증 데이터 크기:50
#2 검증 세트 인덱스: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, \검증 데이터 크기:50
#3 검증 세트 인덱스: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9666666666666667


In [ ]:
from sklearn.model_selection import cross_val_score, cross_validate

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data= iris_data.data
label= iris_data.target

scores = cross_val_score(dt_clf, data, label,
                         scoring='accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores,4))
print('평균 검증 정확도', np.round(np.mean(scores),4))


교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도 0.9667


In [ ]:
from sklearn.model_selection import GridSearchCV

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()
parameters = {'max_depth': [1,2,3], 'min_samples_split': [2,3]}

In [ ]:
import pandas as pd

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

grid_dtree.fit(X_train, y_train)

scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score', 'rank_test_score','split0_test_score',
           'split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [ ]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSerchCV 최고 정확도: {0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSerchCV 최고 정확도: 0.9750


In [ ]:
estimator = grid_dtree.best_estimator_

pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도: 0.9667
